name: places
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.2"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter
  intl: ^0.17.0
 
  provider: ^6.0.3
  shared_preferences: ^2.0.15

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^4.10.1
  surf_lint_rules: ^1.4.1


flutter:
  generate: true
  uses-material-design: true

  assets:
    - res/
    - res/icons/
    - res/icons/catalog/
    - res/icons/tutorial/
    - res/icons/empty_pages/


  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: res/fonts/Roboto-Light.ttf
          weight: 300
        - asset: res/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: res/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: res/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: res/fonts/Roboto-Black.ttf
          weight: 900
        - asset: res/fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: res/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: res/fonts/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: res/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: res/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: res/fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
  
